[tasks.strip]
command = "riscv64-linux-gnu-strip"
args= [
    "target/riscv32imac-unknown-none-elf/release/blink",
]

[tasks.objcopy]
command = "riscv64-linux-gnu-objcopy"
args= [
    "-O", "binary",
    "target/riscv32imac-unknown-none-elf/release/blink",
    "target/riscv32imac-unknown-none-elf/release/blink.bin"
]
dependencies = ["strip"]
