on: [push]

jobs:
  clean-verilog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Checkout source
    - uses: reviewdog/action-setup@v1 # Setup reviewdog
    - name: Verilog Cleaner
      uses: SuibianP/verilog-cleaner@v0.1.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
