name: Rust

on:
  push:
    paths:
      - firmware/**

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: firmware

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add toolchain
      run: rustup target add riscv32i-unknown-none-elf

    - name: Add binutils from cargo
      run: rustup component add llvm-tools-preview

    - name: Get the gcc for riscv32i
      run: sudo dpkg --add-architecture riscv64 && sudo apt install gcc-riscv64-linux-gnu

    - name: Build
      run: cargo build --verbose

    # - name: Run tests
      # run: cargo test --verbose
