name: Rust

on:
  push:
    paths:
      - firmware/**

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: firmware

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add toolchain
      run: rustup target add riscv32imac-unknown-none-elf
    - name: Build
      run: cargo build --verbose
    # - name: Run tests
      # run: cargo test --verbose
